name: HCL OneTest API

on:
    workflow_dispatch:
        inputs:
            configType:
                description: 'Configuration Type'
                required: true
            productPath:
                description: 'Product Path'
                required: true
            projectDir:
                description: 'Project Directory'
                required: true
            projectName:
                description: 'Project Name'
                required: true
            environment:
                description: 'Environment'
                required: true
            tests:
                description: 'Test(s) to run'
                required: true
            junitDir:
                description: 'JunitDir'
                required: false

jobs:

    WebUI-Action:
        runs-on: self-hosted
        name: HCL OneTest API
        steps:
         - name: HCL OneTest API
           uses: SonaHJ/APIAction@main
           with:
            configType: '${{ github.event.inputs.configType }}'
            productPath: '${{ github.event.inputs.productPath }}'
            projectDir: '${{ github.event.inputs.projectDir }}'
            projectName: '${{ github.event.inputs.projectName }}'
            environment: '${{ github.event.inputs.environment }}'
            tests: '${{ github.event.inputs.tests }}'
            junitDir: '${{ github.event.inputs.junitDir }}'
